### ISSUE TITLE
Define a clouds.yaml for password/username/url etc

### ISSUE THREAD

**Issue by jichenjc** [multicloudlab/cluster-api-provider-ibmcloud#18]
/kind feature

define a clouds.yaml for access to the ibm cloud, e.g cloud location, region, password, username etc

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by xunpan** [comment]
clouds.yaml is created.

Currently, we have `userName` and `apiKey`. It is enough to create VM instances on IBM cloud. For datacenter, it is defined in Machine. 

@jichenjc, do you have comments on any other information needed to define in clouds.yaml?

**Comment by gyliu513** [comment]
Let's trace this task in https://github.com/multicloudlab/cluster-api-provider-ibmcloud/issues/62
