### ISSUE TITLE
userdata creation (for k8s cluster startup)

### ISSUE THREAD

**Issue by jichenjc** [multicloudlab/cluster-api-provider-ibmcloud#19]
/kind feature
need provide a set of configuration scripts for the new deployed guest to run this 
in order to boot cluster and join cluster for master/node 

cloud-init will be primary focus for this PR

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
Sub tasks:
- [ ] Investigate how user-data works in SL
- [ ] Hard-code user-date for master and work
- [ ] Update user-data to be more generic

**Comment by jichenjc** [comment]
The user-data actually need to be delivered into at least ubuntu and rhel based ...

**Comment by jichenjc** [comment]
@xunpan do you want to take this one? this might take some time ... or you may select your prefer by assign your self to other issues...

**Comment by xunpan** [comment]
I will start from Ubuntu with a Kubernetes deployment scripts

**Comment by xunpan** [comment]
Finished scripts. 
I will try to understand IBM Cloud bootstrap script execution and try to `Create` machine from code.

**Comment by xunpan** [comment]
update script based on runtime information
https://github.com/multicloudlab/cluster-api-provider-ibmcloud/pull/39

To make script run in softlay, we need a script file hosting place. Currently, I'd like to implement a github one.

**Comment by xunpan** [comment]
Try to understand how to use `userData` to execute a script in softlayer. 
A ticket is logged to trace the related information. https://github.com/softlayer/softlayer-go/issues/133

**Comment by xunpan** [comment]
The related part should be done.
After we have related yaml files generated, we can test it. Just close it.
