### ISSUE TITLE
kustomize generation for yamls 

### ISSUE THREAD

**Issue by jichenjc** [multicloudlab/cluster-api-provider-ibmcloud#21]
/kind feature

need provide kustomize for create something like cluster-api image defintion, cloud secrets, include from cluster-api definition etc

go to cluster-api-provider-openstack/cmd/clusterctl/examples/openstack for further info

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
I'd like the sub-task as follows:

- [ ] Create hard-code `cluster.yaml`, `machines.yaml` and `provider-components.yaml` to make sure the whole process works
- [ ] Create kind of `generate_yaml.sh` to leverage `kustomize` to generate the above three files.

**Comment by jichenjc** [comment]
yes, it can be divided into 2 parts (or even more), thanks for the comments

**Comment by xunpan** [comment]
Do you mind to close this ticket if have no other comments. 
Current generation script can generate .yaml with kustomize correctly.
