### ISSUE TITLE
Enable travis for cluster API

### ISSUE THREAD

**Issue by gyliu513** [multicloudlab/cluster-api-provider-ibmcloud#23]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

We can follow https://github.com/kubernetes-sigs/federation-v2/blob/master/.travis.yml to enable travis for our project.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gyliu513** [comment]
I will check how to turn on travis for this repo at https://travis-ci.com/account/repositories

FYI @jichenjc @morvencao

**Comment by gyliu513** [comment]
@morvencao CI failed, please help check https://github.com/multicloudlab/cluster-api-provider-ibmcloud/pull/30

**Comment by morvencao** [comment]
Fixed in https://github.com/multicloudlab/cluster-api-provider-ibmcloud/pull/32, let's close this.
